export default {
  HEROES_LIST_LOAD_SUCCEED: 'HEROES_LIST_LOAD_SUCCEED',
  HEROES_LIST_LOAD_ERROR: 'HEROES_LIST_LOAD_ERROR',
  HEROE_DETAIL_LOAD_SUCCEED: 'HEROE_DETAIL_LOAD_SUCCEED',
  HEROE_DETAIL_LOAD_ERROR: 'HEROE_DETAIL_LOAD_ERROR'
};
